### ISSUE TITLE
Missing opencv_test dependency?

### ISSUE THREAD

**Issue by bit-pirate** [ros-perception/vision_opencv#1]
Hi there!

Once of my Turtlebot apps, which I am trying to get running crashes due to a missing dependency in cv_bridge. It is pulling in opencv_tests(*), which are not listed in the package.xml.

(*) in cv_bridge/src/cv_bridge/cv_bridge.py

```
import roslib
roslib.load_manifest('opencv_tests')
import rostest
import rospy
import unittest

import sensor_msgs.msg
import cv
```

Is that a bug or am I missing something?

PS: Here is the original bug:  https://github.com/turtlebot/turtlebot_apps/issues/23
PPS: In case opencv_tests is really needed, will you release it as well?

**Comment by vrabaud** [comment]
wow, nice. opencv_tests is just a bunch of tests, no application or library. So I do not see why cv_bridge depends on it.
Can you please remove the second line "roslib.load_manifest('opencv_tests')" and tell me if that works for you ? thx

**Comment by derekjchow** [comment]
I can confirm that removing the second lines causes the package to run.

**Comment by vrabaud** [comment]
thx for the bug report. 1.9.11 fixes that.

**Comment by bit-pirate** [comment]
Cool! I couldn't thoroughly test it, since I'm struggling with Groovy and OpenNi here. But at least I can state, that the program was runnable with the opencv_tests dependency removed.
