### ISSUE TITLE
Need to check if all distortion coefficients are zero, not just first one

### ISSUE THREAD

**Issue by lucasw** [ros-perception/vision_opencv#117]
To support https://github.com/ros-perception/image_pipeline/issues/180 PinholeCameraModel::fromCameraInfo() needs to check if any of the distortion coefficients are non-zero, not just the first one.

https://github.com/ros-perception/vision_opencv/blob/indigo/image_geometry/src/pinhole_camera_model.cpp#L130

```
cache_->distortion_state = (cam_info_.D.size() == 0 || (cam_info_.D[0] == 0.0)) ? NONE : CALIBRATED;
```

**Comment by vrabaud** [comment]
ok, please make your pull request here first then. Thx

**Comment by lucasw** [comment]
I'll make a test here also.

**Comment by vrabaud** [comment]
Close by #118
