### ISSUE TITLE
[opencv_apps] improvement proposal 

### ISSUE THREAD

**Issue by kochigami** [ros-perception/vision_opencv#121]
Hi

I tried to use opencv_apps by reading http://wiki.ros.org/opencv_apps, but there is no example launch file for this, so I'd like to propose installing test directory for example launch file

I tried to run camsift, but at first it did not show anything, and it takes few minutes to understand 
1) we need gui param to show display
2) we need histogram param to start program
I think it is better to display these information or change code to run by `rosrun opencv_apps camshift image:=image_raw`

Cc: @k-okada

**Comment by vrabaud** [comment]
opencv_apps is now its own repo: https://github.com/ros-perception/opencv_apps/issues/1
