### ISSUE TITLE
Type conversion errors compiling image_pipeline

### ISSUE THREAD

**Issue by mikepurvis** [ros-perception/vision_opencv#134]
Recent changes in `vision_opencv` have broken `image_pipeline` in Indigo. Please see issue reported here:

https://github.com/ros-perception/image_pipeline/issues/197

I believe the issue was introduced in 2b75bdc13b3b41ed65d4d66e4eae16453e1d0242, though it's not immediately obvious to me what the fix is (other than to potentially just revert that?)

@wkentaro

**Comment by wkentaro** [comment]
https://github.com/ros-perception/image_pipeline/issues/197#issuecomment-223118322

**Comment by vrabaud** [comment]
Fixed with the latest official release.
