### ISSUE TITLE
release fix for dependency on catkin into hydro

### ISSUE THREAD

**Issue by dirk-thomas** [ros-perception/vision_opencv#15]
While the issue has been fixed long time ago f5f5d206159ddf903a5345e1e1e2771630db7591 it has not been released since than.

**Comment by vrabaud** [comment]
I did not think it mattered as no error popped. Releasing now

**Comment by dirk-thomas** [comment]
Was not important - but one of three packages in Hydro notoriously complaining on the console when doing package crawling. Thanks for releasing it so fast.
