### ISSUE TITLE
Corrupt JPEG data: extraneous bytes before marker

### ISSUE THREAD

**Issue by Naws-EBMS** [ros-perception/vision_opencv#160]
Greetings,

I am having some issues after installing the cv_bridge package for ROS (Kinetic on ubuntu 16.04).
prior to installing cv_bridge streaming from my camera worked flawlessly through openCV, however after installing cv_bridge, i now get a warning messages : "Corrupt JPEG data: # extraneous bytes before marker 0xXX"

this appears to give memory allocation issues when trying to stream through ROS:
VIDIOC_REQBUFS: Cannot allocate memory
VIDIOC_QBUF: Bad file descriptor

swapping to a different camera, the ROS streamer appears to be stable but throws warnings rather than having a memory allocation issue:
"Corrupt JPEG data: # extraneous bytes before marker 0xXX"

has anyone else had anything like this or any idea where the problem lies?

Cheers,
Aaron

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue has not been active for a while, I'm going to close it due to inactivity. Please feel free to comment if it is still relevant and you would like to get it re-opened.
