### ISSUE TITLE
Cannot find source file:      test_compression.cpp

### ISSUE THREAD

**Issue by wangzhaodong123** [ros-perception/vision_opencv#171]
When i make my space ,the problem happened:
CMake Error at /opt/ros/indigo/share/catkin/cmake/test/gtest.cmake:79 (add_executable):
  Cannot find source file:
    test_compression.cpp
  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
Call Stack (most recent call first):
  /opt/ros/indigo/share/catkin/cmake/test/gtest.cmake:34 (catkin_add_executable_with_gtest)
  vision_opencv/cv_bridge/test/CMakeLists.txt:6 (catkin_add_gtest)
Can you help me solve this problem? Thank you.

**Comment by vrabaud** [comment]
Thx for reporting. The continuous integration warned me but I was too far from my computer ... Thx!
