### ISSUE TITLE
groovy libopencv_calib3d link error

### ISSUE THREAD

**Issue by daemacles** [ros-perception/vision_opencv#18]
ROS Groovy
Ubuntu 12.04
Catkin

There is a bug in /opt/ros/groovy/share/OpenCV/OpenCVConfig.cmake when trying to link libopencv_calib3d.so.

Pre-fix, this error message is generated:

/usr/bin/ld: CMakeFiles/show_image.dir/src/show_image.cpp.o: undefined reference to symbol '_ZN2cv8solvePnPERKNS_11_InputArrayES2_S2_S2_RKNS_12_OutputArrayES5_bi'
/usr/bin/ld: note: '_ZN2cv8solvePnPERKNS_11_InputArrayES2_S2_S2_RKNS_12_OutputArrayES5_bi' is defined in DSO /opt/ros/groovy/lib/libopencv_calib3d.so.2.4 so try adding it to the linker command line
/opt/ros/groovy/lib/libopencv_calib3d.so.2.4: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: **\* [/home/jay/research/s2p/catkin_ws/devel/lib/opencv_test/show_image] Error 1
make[1]: **\* [opencv_test/CMakeFiles/show_image.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

To fix it, edit OpenCVConfig.cmake and move opencv_calib3d before opencv_core on line 109 ( SET(OpenCV_LIB_COMPONENTS...)

diff:

109c109
## < SET(OpenCV_LIB_COMPONENTS opencv_videostab;opencv_video;opencv_ts;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_calib3d;opencv_core;opencv_contrib)

> SET(OpenCV_LIB_COMPONENTS opencv_videostab;opencv_video;opencv_ts;opencv_superres;opencv_stitching;opencv_photo;opencv_objdetect;opencv_nonfree;opencv_ml;opencv_legacy;opencv_imgproc;opencv_highgui;opencv_gpu;opencv_flann;opencv_features2d;opencv_core;opencv_contrib;opencv_calib3d)

**Comment by vrabaud** [comment]
When do you get that error ? It seems it is a custom file you are trying to compile. What does your CMake and .cpp files look like ?
The file you are asking to modify is the standard OpenCV one and it's been used in way more contexts than ROS itself so a bug there seems unlikely.
Also, what is your gcc version ? (ordering those libraries should not matter). Thx

**Comment by daemacles** [comment]
Sorry, this was a case of user error.  There is no real bug.

A combination of stale and partially misconfigured CMakeLists.txt led to the bizarre condition where the change above fixed things for me.

**Comment by vrabaud** [comment]
yay ! I love bugs that close themselves :p
