### ISSUE TITLE
File references

### ISSUE THREAD

**Issue by BirgitvH** [ros-perception/vision_opencv#186]
I am trying to install this package on ROS indigo (I use Ubuntu 14.04), however I get the error that the target "opencv_core" references the file  "/usr/local/lib/libopencv_core.so.3.0.0", but this file does not exist. 
How can I get this file? 

Thanks in advance!

**Comment by k-okada** [comment]
On indigo, we're expecting to use `/usr/lib/x86_64-linux-gnu/libopencv_core.so`, not opencv3, not files within '/usr/local'. I suppose you once installed opencv3 by yourself and that breaks your environment.
Please remove custom installed opencv3 files from /usr/local, and try again.

**Comment by BirgitvH** [comment]
Thanks!
