### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by wanghuayou1028** [ros-perception/vision_opencv#190]
//common recive image
#include <ros/ros.h>
#include <image_transport/image_transport.h>
#include <opencv2/highgui/highgui.hpp>
#include <cv_bridge/cv_bridge.h>

namespace enc = sensor_msgs::image_encodings;

void imageCallback(const sensor_msgs::ImageConstPtr& msg)
{
   cv_bridge::CvImageConstPtr cv_ptr;
   try
   {
      if (enc::isColor(msg->encoding))
         cv_ptr = cv_bridge::toCvShare(msg,enc::BGR8);
      else
         cv_ptr = cv_bridge::toCvShare(msg, enc::MONO8);
      
      cv::imshow("view", cv_ptr->image);
   }
   catch (cv_bridge::Exception& e)
   {
      ROS_ERROR("cv_bridge exception: %s", e.what());
      return;
   }
   
     // Process cv_ptr->image using OpenCV
}

int main(int argc, char **argv)
{
  ros::init(argc, argv, "image_listener");
  ros::NodeHandle nh;
  cv::namedWindow("view");
  cv::startWindowThread();
  image_transport::ImageTransport it(nh);
  image_transport::Subscriber sub = it.subscribe("/camera/image_raw", 1, imageCallback);
  ros::spin();
  cv::destroyWindow("view");
}

I run this code, core dumped occored, but if the topic is convert to /camera/image_color, this problem will not happend.

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue has not been active for a while, I'm going to close it due to inactivity. Please feel free to comment if it is still relevant and you would like to get it re-opened.
