### ISSUE TITLE
Unknown encoding H?

### ISSUE THREAD

**Issue by void-robotics** [ros-perception/vision_opencv#195]
Hello,

When i use the following callback using a normal image_transport::ImageTransport technique it get the data successfully:
![image](https://user-images.githubusercontent.com/2744891/33999415-6ce8896c-e0b8-11e7-9faa-27031250659f.png)

But when I put the same code in a class ImageTransporter, it fails with the std::exception `Unknown encoding H?`:
![image](https://user-images.githubusercontent.com/2744891/33999504-aba6be94-e0b8-11e7-9932-fe7369f40b9d.png)

I can verify I made sure the encoding is sensor_msgs::image_encodings::MONO16.

The weird thing is that this class's callback does work for my 2d camera. I don't think this is a coding bug, but possibly something with `cv_bridge`. Any ideas?

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue has not been active for a while, I'm going to close it due to inactivity. Please feel free to comment if it is still relevant and you would like to get it re-opened.
