### ISSUE TITLE
cv::VideoCapture codec support in 3.3.1

### ISSUE THREAD

**Issue by Dominik-FKIE** [ros-perception/vision_opencv#198]
Hello,
it seems that there is no support for MJPEG streams (and possibly other codecs?) compiled into the latest version 3.3.1.
I used a manually compiled OpenCV before, and there it was no problem to open a Logitech webcam in MJPEG mode using the "cv_camera" nodelet (param cv_cap_prop_fourcc=1296715847). However, with your latest version it falls back to raw streams. Thus I can only read 5fps in FHD.

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue has not been active for a while, I'm going to close it due to inactivity. Please feel free to comment if it is still relevant and you would like to get it re-opened.
