### ISSUE TITLE
ROS  Kinetic for OpenCV 2.4.13

### ISSUE THREAD

**Issue by AlexWan1027** [ros-perception/vision_opencv#200]
I want to use OpenCV 2.4.13, and edit the configuration file of cv_bridge's package for OpenCV 2.4.13. Although it can make the project compile successfully, running the project will failed to read image and prompt me "core " in the terminal. What is the difference between the cv_bridge of indigo and kinetic.

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue is raised against a distros that are no longer supported, I'm going to close it out. Please feel free to comment if it is still relevant and you would like to get it re-opened.
