### ISSUE TITLE
Upstream and maintain ROS2 cv_bridge

### ISSUE THREAD

**Issue by gaoethan** [ros-perception/vision_opencv#203]
ROS2 is the next newer ROS and we have already ported [ROS2 cv_bridge](https://github.com/gaoethan/vision_opencv/tree/ros2_cv_bridge) for ROS2 on the basis of forking from the ROS kenetic branch. you know, cv_bridge is important to use ROS with OpenCV and we intend to upstream this ROS2 porting to benefit more ROS2 users to use OpenCV in their perception applications. and we had a simple thread to talking this within ROS2 forking of vision_opencv before (you can find the details [HERE](https://github.com/ros2/vision_opencv/issues/12)).
Generally we can consider the following options:

-     Option 1: maintain a separate project under the umbrella of ROS2
-     Option 2: create a ROS2 branch in ROS vision_opencv and merge back the ROS2 porting accordingly
-     Option 3: Self-maintain if no buy-in
-     Option 4: ???

I'm here to check with your comments to this upstream @vrabaud  ? Obviously, I have to agree that it increases the work to maintain ROS and ROS2 at the same time, so I'm not sure how do you think of this upstream and please share your comments, thanks a lot !

**Comment by mikaelarguedas** [comment]
A ros2 branch has been created on this repository, it currently is on par with the kinetic branch.

Quick summary of my understanding:
 - from https://github.com/ros2/vision_opencv/issues/12#issuecomment-374485888, @gaoethan will maintain the ros2 branch
- gaoethan will get write access to the repository and will review / merge incoming PRs on the ros2 branch.
- vrabaud will keep maintaining the ROS 1 branches.

@gaoethan @vrabaud feel free to comment here with any additional information/clarification.

**Comment by gaoethan** [comment]
No problem for me and thanks for your great support @mikaelarguedas @vrabaud

**Comment by gaoethan** [comment]
@mikaelarguedas @vrabaud Just now I tried to submit a PR to the `ros2` branch in order to have a basic checking, and the CI job was triggered accordingly, however, I think that the CI job started is for the original ROS and that doesn't work for ROS2 generally, it requires a ROS2 CI environment. additionally, it seems that I don't get the write access to the ROS2 branch to merge the PR to `ros2` branch, Could u please have a check ? thanks a lot!

**Comment by mikaelarguedas** [comment]
I created a `vision_opencv_ros2_maintainers` team on the ros-perception organization. I don;t have the permissions to invite you to the organization / add you to the team.
@dirk-thomas @vrabaud or @tfoote can one of you invite @gaoethan ?

**Comment by dirk-thomas** [comment]
I invited @gaoethan. @mikaelarguedas Do you think the current "write" permission is sufficient? Not sure which actions need "admin"...

**Comment by mikaelarguedas** [comment]
"write" should allow to push changes, create branches and merge PRs. I think that should be sufficient

**Comment by gaoethan** [comment]
Ok, thanks for the permission granted, let me try to upstream the previous porting firstly and back to you if any problem. thanks !
