### ISSUE TITLE
package conflict

### ISSUE THREAD

**Issue by juki21c** [ros-perception/vision_opencv#21]
I am using Ubuntu 12.10 and ROS Groovy. 'ros-groovy-cv-bridge' depends on libavcodec53 and libavutil51, which conflicts with some other packages in Ubuntu.

For example, 'webots' depends on libavcode-extra-53 and libavutil-extra-51. However, libavcodec53 conflicts with libavcodec-extra-53, and libavutil51 conflicts with libavutil-extra-51. I cannot install both ros-groovy-cv-bridge and webots.

**Comment by vrabaud** [comment]
weird, I have  libavcode-extra-53 and libavutil-extra-51 installed on my machine and ros-groovy-opencv2 installed. The extra packages replace the other ones so it should be transparent.
Also, no Ubuntu package depends on the extra packages, it is a bad thing to do. What does it tell you when you install the extra packages ?

**Comment by juki21c** [comment]
I tried it with three different computers (Ubuntu 12.10 and Groovy) and got the same results. Initially, libavcodec-extra-53 and libavutil-extra-51 are installed, but libavcodec53 and libavutil51 are not. Here are what it says:

$ sudo apt-get install ros-groovy-opencv2
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  collada-dom-dev collada-dom2.4-dp-base collada-dom2.4-dp-dev freeglut3
  freeglut3-dev hddtemp libasound2-dev libassimp-dev libassimp3
  libavahi-client-dev libavahi-common-dev libbz2-dev libcaca-dev libcf0
  libcppunit-1.12-1 libcppunit-dev libcurl4-openssl-dev libdbus-1-dev
  libfltk1.1 libfltk1.1-dev libfreeimage-dev libfreeimage3 libgcrypt11-dev
  libgl2ps-dev libgl2ps0 libgnutls-dev libgnutls-openssl27 libgnutlsxx27
  libgpg-error-dev libhdf5-7 libidn11-dev libilmbase6 libjs-sphinxdoc
  libjs-underscore libnetcdf-dev libnetcdfc++4 libnetcdfc7 libnetcdff5
  libnetpbm10 libnetpbm10-dev libodbc1 libogre-1.7.4 libogre-dev libopenexr6
  libp11-kit-dev libpoco-dev libpococrypto9 libpocodata9 libpocofoundation9
  libpocomysql9 libpoconet9 libpoconetssl9 libpocoodbc9 libpocosqlite9
  libpocoutil9 libpocoxml9 libpocozip9 libprotobuf-dev libprotobuf-lite7
  libprotoc-dev libpulse-dev libqhull-dev libqhull5 libqwt-dev libqwt5-qt4
  libqwt6 librtmp-dev libsdl-image1.2 libsdl-image1.2-dev libsdl1.2-dev
  libslang2-dev libtar-dev libtar0 libtasn1-3-dev libtbb-dev libtbb2
  libusb-1.0-0-dev libvtk5.8 libwebp2 libxaw7-dev libxml2-dev libxmu-dev
  libxmu-headers libxpm-dev libxss-dev libyaml-cpp-dev libyaml-cpp0.3
  libyaml-dev libzzip-0-13 libzzip-dev linux-headers-3.5.0-17 python-epydoc
  python-jinja2 python-matplotlib python-matplotlib-data python-opengl
  python-pydot python-pyparsing python-qt4-gl python-qwt5-qt4 python-sphinx
  python-tz ros-groovy-actionlib ros-groovy-actionlib-msgs ros-groovy-angles
  ros-groovy-bfl ros-groovy-bond ros-groovy-bond-core ros-groovy-bondcpp
  ros-groovy-bondpy ros-groovy-bullet ros-groovy-camera-calibration-parsers
  ros-groovy-camera-info-manager ros-groovy-class-loader
  ros-groovy-collada-parser ros-groovy-collada-urdf ros-groovy-common
  ros-groovy-common-msgs ros-groovy-common-rosdeps ros-groovy-common-tutorials
  ros-groovy-console-bridge ros-groovy-convex-decomposition
  ros-groovy-diagnostic-aggregator ros-groovy-diagnostic-analysis
  ros-groovy-diagnostic-common-diagnostics ros-groovy-diagnostics
  ros-groovy-documentation ros-groovy-driver-base ros-groovy-driver-common
  ros-groovy-dynamic-reconfigure ros-groovy-eigen-conversions
  ros-groovy-executive-smach ros-groovy-filters ros-groovy-flann
  ros-groovy-gencpp ros-groovy-genlisp ros-groovy-geometry
  ros-groovy-geometry-experimental ros-groovy-geometry-tutorials
  ros-groovy-image-common ros-groovy-image-transport
  ros-groovy-interactive-markers ros-groovy-ivcon ros-groovy-kdl-conversions
  ros-groovy-kdl-parser ros-groovy-laser-geometry ros-groovy-message-filters
  ros-groovy-message-generation ros-groovy-mk ros-groovy-nav-msgs
  ros-groovy-nodelet ros-groovy-nodelet-core ros-groovy-nodelet-topic-tools
  ros-groovy-orocos-kdl ros-groovy-pcl-msgs ros-groovy-physics-ode
  ros-groovy-pluginlib ros-groovy-polled-camera ros-groovy-qt-dotgraph
  ros-groovy-qt-gui-app ros-groovy-qt-gui-core ros-groovy-qt-gui-cpp
  ros-groovy-qt-gui-py-common ros-groovy-resource-retriever
  ros-groovy-robot-model ros-groovy-robot-model-tutorials
  ros-groovy-robot-model-visualization ros-groovy-robot-state-publisher
  ros-groovy-ros ros-groovy-ros-comm ros-groovy-ros-tutorials
  ros-groovy-rosbag ros-groovy-rosbash ros-groovy-rosboost-cfg
  ros-groovy-rosbuild ros-groovy-rosclean ros-groovy-rosconsole-bridge
  ros-groovy-roscpp-tutorials ros-groovy-roscreate ros-groovy-roslaunch
  ros-groovy-rosmake ros-groovy-rosmaster ros-groovy-rosmsg ros-groovy-rosnode
  ros-groovy-rosout ros-groovy-rosparam ros-groovy-rospy-tutorials
  ros-groovy-rosservice ros-groovy-rostest ros-groovy-rostopic
  ros-groovy-rosunit ros-groovy-roswtf ros-groovy-rqt-action
  ros-groovy-rqt-bag ros-groovy-rqt-bag-plugins ros-groovy-rqt-console
  ros-groovy-rqt-dep ros-groovy-rqt-graph ros-groovy-rqt-gui-cpp
  ros-groovy-rqt-launch ros-groovy-rqt-logger-level ros-groovy-rqt-moveit
  ros-groovy-rqt-msg ros-groovy-rqt-nav-view ros-groovy-rqt-plot
  ros-groovy-rqt-pose-view ros-groovy-rqt-publisher ros-groovy-rqt-py-common
  ros-groovy-rqt-py-console ros-groovy-rqt-reconfigure
  ros-groovy-rqt-robot-dashboard ros-groovy-rqt-robot-monitor
  ros-groovy-rqt-robot-steering ros-groovy-rqt-runtime-monitor
  ros-groovy-rqt-service-caller ros-groovy-rqt-shell ros-groovy-rqt-srv
  ros-groovy-rqt-tf-tree ros-groovy-rqt-topic ros-groovy-rqt-web
  ros-groovy-self-test ros-groovy-shape-msgs ros-groovy-smclib ros-groovy-srdf
  ros-groovy-srdfdom ros-groovy-stage ros-groovy-stereo-msgs ros-groovy-tf
  ros-groovy-tf-conversions ros-groovy-tf2 ros-groovy-tf2-geometry-msgs
  ros-groovy-tf2-kdl ros-groovy-tf2-msgs ros-groovy-tf2-ros
  ros-groovy-tf2-tools ros-groovy-timestamp-tools ros-groovy-topic-tools
  ros-groovy-trajectory-msgs ros-groovy-turtlesim ros-groovy-urdf
  ros-groovy-urdf-interface ros-groovy-urdf-parser ros-groovy-urdfdom
  ros-groovy-urdfdom-headers ros-groovy-visualization-msgs ros-groovy-xacro
  sphinx-common sphinx-doc tcl8.5-dev tk8.5-dev x11proto-scrnsaver-dev
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libavcodec-dev libavcodec53 libavformat-dev libavutil-dev libavutil51
  libswscale-dev
Suggested packages:
  libdc1394-22-dev libgsm1-dev libraw1394-dev libschroedinger-dev libspeex-dev
  libvorbis-dev
The following packages will be REMOVED:
  libavcodec-extra-53 libavutil-extra-51 webots
The following NEW packages will be installed:
  libavcodec-dev libavcodec53 libavformat-dev libavutil-dev libavutil51
  libswscale-dev ros-groovy-opencv2
0 upgraded, 7 newly installed, 3 to remove and 1 not upgraded.
Need to get 16.5 MB of archives.
After this operation, 506 MB disk space will be freed.
Do you want to continue [Y/n]?

**Comment by vrabaud** [comment]
tried again from scratch for me and it works. Nobody complained about that before. Where did you get your webot package ? To me it comes from there. Just uninstall it, and try having only libavcodec-extra-53 libavutil-extra-51 and ros-groovy-opencv2.
Maybe you got you extra from a weird ppa ?

**Comment by juki21c** [comment]
Thank you for your help. I got 'webots' from http://www.cyberbotics.com/debian/binary-amd64.
I uninstalled 'webots'. I still have libavcodec-extra-53 and libavutil-extra-51 installed. I try to install ros-groovy-opencv2 again. It says:

$ sudo apt-get install ros-groovy-opencv2
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  collada-dom-dev collada-dom2.4-dp-base collada-dom2.4-dp-dev freeglut3
  freeglut3-dev hddtemp libasound2-dev libassimp-dev libassimp3
  libavahi-client-dev libavahi-common-dev libbz2-dev libcaca-dev libcf0
  libcppunit-1.12-1 libcppunit-dev libcurl4-openssl-dev libdbus-1-dev
  libfltk1.1 libfltk1.1-dev libfreeimage-dev libfreeimage3 libgcrypt11-dev
  libgl2ps-dev libgl2ps0 libgnutls-dev libgnutls-openssl27 libgnutlsxx27
  libgpg-error-dev libhdf5-7 libidn11-dev libilmbase6 libjs-sphinxdoc
  libjs-underscore libnetcdf-dev libnetcdfc++4 libnetcdfc7 libnetcdff5
  libnetpbm10 libnetpbm10-dev libodbc1 libogre-1.7.4 libogre-dev libopenexr6
  libp11-kit-dev libpoco-dev libpococrypto9 libpocodata9 libpocofoundation9
  libpocomysql9 libpoconet9 libpoconetssl9 libpocoodbc9 libpocosqlite9
  libpocoutil9 libpocoxml9 libpocozip9 libprotobuf-dev libprotobuf-lite7
  libprotoc-dev libpulse-dev libqhull-dev libqhull5 libqwt-dev libqwt5-qt4
  libqwt6 librtmp-dev libsdl-image1.2 libsdl-image1.2-dev libsdl1.2-dev
  libslang2-dev libtar-dev libtar0 libtasn1-3-dev libtbb-dev libtbb2
  libusb-1.0-0-dev libvtk5.8 libwebp2 libxaw7-dev libxml2-dev libxmu-dev
  libxmu-headers libxpm-dev libxss-dev libyaml-cpp-dev libyaml-cpp0.3
  libyaml-dev libzzip-0-13 libzzip-dev linux-headers-3.5.0-17 python-epydoc
  python-jinja2 python-matplotlib python-matplotlib-data python-opengl
  python-pydot python-pyparsing python-qt4-gl python-qwt5-qt4 python-sphinx
  python-tz ros-groovy-actionlib ros-groovy-actionlib-msgs ros-groovy-angles
  ros-groovy-bfl ros-groovy-bond ros-groovy-bond-core ros-groovy-bondcpp
  ros-groovy-bondpy ros-groovy-bullet ros-groovy-camera-calibration-parsers
  ros-groovy-camera-info-manager ros-groovy-class-loader
  ros-groovy-collada-parser ros-groovy-collada-urdf ros-groovy-common
  ros-groovy-common-msgs ros-groovy-common-rosdeps ros-groovy-common-tutorials
  ros-groovy-console-bridge ros-groovy-convex-decomposition
  ros-groovy-diagnostic-aggregator ros-groovy-diagnostic-analysis
  ros-groovy-diagnostic-common-diagnostics ros-groovy-diagnostics
  ros-groovy-documentation ros-groovy-driver-base ros-groovy-driver-common
  ros-groovy-dynamic-reconfigure ros-groovy-eigen-conversions
  ros-groovy-executive-smach ros-groovy-filters ros-groovy-flann
  ros-groovy-gencpp ros-groovy-genlisp ros-groovy-geometry
  ros-groovy-geometry-experimental ros-groovy-geometry-tutorials
  ros-groovy-image-common ros-groovy-image-transport
  ros-groovy-interactive-markers ros-groovy-ivcon ros-groovy-kdl-conversions
  ros-groovy-kdl-parser ros-groovy-laser-geometry ros-groovy-message-filters
  ros-groovy-message-generation ros-groovy-mk ros-groovy-nav-msgs
  ros-groovy-nodelet ros-groovy-nodelet-core ros-groovy-nodelet-topic-tools
  ros-groovy-orocos-kdl ros-groovy-pcl-msgs ros-groovy-physics-ode
  ros-groovy-pluginlib ros-groovy-polled-camera ros-groovy-qt-dotgraph
  ros-groovy-qt-gui-app ros-groovy-qt-gui-core ros-groovy-qt-gui-cpp
  ros-groovy-qt-gui-py-common ros-groovy-resource-retriever
  ros-groovy-robot-model ros-groovy-robot-model-tutorials
  ros-groovy-robot-model-visualization ros-groovy-robot-state-publisher
  ros-groovy-ros ros-groovy-ros-comm ros-groovy-ros-tutorials
  ros-groovy-rosbag ros-groovy-rosbash ros-groovy-rosboost-cfg
  ros-groovy-rosbuild ros-groovy-rosclean ros-groovy-rosconsole-bridge
  ros-groovy-roscpp-tutorials ros-groovy-roscreate ros-groovy-roslaunch
  ros-groovy-rosmake ros-groovy-rosmaster ros-groovy-rosmsg ros-groovy-rosnode
  ros-groovy-rosout ros-groovy-rosparam ros-groovy-rospy-tutorials
  ros-groovy-rosservice ros-groovy-rostest ros-groovy-rostopic
  ros-groovy-rosunit ros-groovy-roswtf ros-groovy-rqt-action
  ros-groovy-rqt-bag ros-groovy-rqt-bag-plugins ros-groovy-rqt-console
  ros-groovy-rqt-dep ros-groovy-rqt-graph ros-groovy-rqt-gui-cpp
  ros-groovy-rqt-launch ros-groovy-rqt-logger-level ros-groovy-rqt-moveit
  ros-groovy-rqt-msg ros-groovy-rqt-nav-view ros-groovy-rqt-plot
  ros-groovy-rqt-pose-view ros-groovy-rqt-publisher ros-groovy-rqt-py-common
  ros-groovy-rqt-py-console ros-groovy-rqt-reconfigure
  ros-groovy-rqt-robot-dashboard ros-groovy-rqt-robot-monitor
  ros-groovy-rqt-robot-steering ros-groovy-rqt-runtime-monitor
  ros-groovy-rqt-service-caller ros-groovy-rqt-shell ros-groovy-rqt-srv
  ros-groovy-rqt-tf-tree ros-groovy-rqt-topic ros-groovy-rqt-web
  ros-groovy-self-test ros-groovy-shape-msgs ros-groovy-smclib ros-groovy-srdf
  ros-groovy-srdfdom ros-groovy-stage ros-groovy-stereo-msgs ros-groovy-tf
  ros-groovy-tf-conversions ros-groovy-tf2 ros-groovy-tf2-geometry-msgs
  ros-groovy-tf2-kdl ros-groovy-tf2-msgs ros-groovy-tf2-ros
  ros-groovy-tf2-tools ros-groovy-timestamp-tools ros-groovy-topic-tools
  ros-groovy-trajectory-msgs ros-groovy-turtlesim ros-groovy-urdf
  ros-groovy-urdf-interface ros-groovy-urdf-parser ros-groovy-urdfdom
  ros-groovy-urdfdom-headers ros-groovy-visualization-msgs ros-groovy-xacro
  sphinx-common sphinx-doc tcl8.5-dev tk8.5-dev x11proto-scrnsaver-dev
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libavcodec-dev libavcodec53 libavformat-dev libavutil-dev libavutil51
  libswscale-dev
Suggested packages:
  libdc1394-22-dev libgsm1-dev libraw1394-dev libschroedinger-dev libspeex-dev
  libvorbis-dev
The following packages will be REMOVED:
  libavcodec-extra-53 libavutil-extra-51
The following NEW packages will be installed:
  libavcodec-dev libavcodec53 libavformat-dev libavutil-dev libavutil51
  libswscale-dev ros-groovy-opencv2
0 upgraded, 7 newly installed, 2 to remove and 1 not upgraded.
Need to get 16.5 MB of archives.
After this operation, 53.2 MB of additional disk space will be used.
Do you want to continue [Y/n]?

**Comment by vrabaud** [comment]
well, just go ahead, install it. And then install libavcodec-extra-53 libavutil-extra-51 . It should not uninstall ros-groovy-opencv2

**Comment by juki21c** [comment]
(I removed webots' source list.) 
I installed ros-groovy-opencv2. I try to install libavcodec-extra-53 again. It says:

$ sudo apt-get install libavcodec-extra-53 
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  collada-dom-dev collada-dom2.4-dp-base collada-dom2.4-dp-dev ffmpeg freeglut3 freeglut3-dev gir1.2-gtk-2.0 hddtemp libasound2-dev libassimp-dev libassimp3 libatk1.0-dev libav-tools
  libavahi-client-dev libavahi-common-dev libavdevice53 libavfilter2 libbz2-dev libcaca-dev libcairo-script-interpreter2 libcairo2-dev libcf0 libcppunit-1.12-1 libcppunit-dev
  libcurl4-openssl-dev libdbus-1-dev libfltk1.1 libfltk1.1-dev libfontconfig1-dev libfreeimage-dev libfreeimage3 libfreetype6-dev libgcrypt11-dev libgdk-pixbuf2.0-dev libgl2ps-dev libgl2ps0
  libglib2.0-dev libgnutls-dev libgnutls-openssl27 libgnutlsxx27 libgpg-error-dev libgtk2.0-dev libhdf5-7 libidn11-dev libilmbase6 libjasper-dev libjbig-dev libjpeg-dev libjpeg-turbo8-dev
  libjpeg8-dev libjs-sphinxdoc libjs-underscore liblzma-dev libnetcdf-dev libnetcdfc++4 libnetcdfc7 libnetcdff5 libnetpbm10 libnetpbm10-dev libodbc1 libogg-dev libogre-1.7.4 libogre-dev
  libopenexr6 libp11-kit-dev libpango1.0-dev libpixman-1-dev libpng12-dev libpoco-dev libpococrypto9 libpocodata9 libpocofoundation9 libpocomysql9 libpoconet9 libpoconetssl9 libpocoodbc9
  libpocosqlite9 libpocoutil9 libpocoxml9 libpocozip9 libprotobuf-dev libprotobuf-lite7 libprotoc-dev libpulse-dev libqhull-dev libqhull5 libqwt-dev libqwt5-qt4 libqwt6 librtmp-dev
  libsdl-image1.2 libsdl-image1.2-dev libsdl1.2-dev libslang2-dev libtar-dev libtar0 libtasn1-3-dev libtbb-dev libtbb2 libtheora-dev libtiff5-dev libtiffxx5 libusb-1.0-0-dev libv4l-dev
  libvtk5.8 libwebp2 libxaw7-dev libxcb-render0-dev libxcb-shm0-dev libxcomposite-dev libxcursor-dev libxft-dev libxi-dev libxinerama-dev libxml2-dev libxml2-utils libxmu-dev libxmu-headers
  libxpm-dev libxrandr-dev libxrender-dev libxss-dev libyaml-cpp-dev libyaml-cpp0.3 libyaml-dev libzzip-0-13 libzzip-dev linux-headers-3.5.0-17 python-epydoc python-jinja2 python-matplotlib
  python-matplotlib-data python-opengl python-pydot python-pyparsing python-qt4-gl python-qwt5-qt4 python-sphinx python-tz ros-groovy-actionlib ros-groovy-actionlib-msgs ros-groovy-angles
  ros-groovy-bfl ros-groovy-bond ros-groovy-bond-core ros-groovy-bondcpp ros-groovy-bondpy ros-groovy-bullet ros-groovy-camera-calibration-parsers ros-groovy-camera-info-manager
  ros-groovy-class-loader ros-groovy-collada-parser ros-groovy-collada-urdf ros-groovy-common ros-groovy-common-msgs ros-groovy-common-rosdeps ros-groovy-common-tutorials
  ros-groovy-console-bridge ros-groovy-convex-decomposition ros-groovy-diagnostic-aggregator ros-groovy-diagnostic-analysis ros-groovy-diagnostic-common-diagnostics ros-groovy-diagnostics
  ros-groovy-documentation ros-groovy-driver-base ros-groovy-driver-common ros-groovy-dynamic-reconfigure ros-groovy-eigen-conversions ros-groovy-executive-smach ros-groovy-filters
  ros-groovy-flann ros-groovy-gencpp ros-groovy-genlisp ros-groovy-geometry ros-groovy-geometry-experimental ros-groovy-geometry-tutorials ros-groovy-image-common ros-groovy-image-transport
  ros-groovy-interactive-markers ros-groovy-ivcon ros-groovy-kdl-conversions ros-groovy-kdl-parser ros-groovy-laser-geometry ros-groovy-message-filters ros-groovy-message-generation
  ros-groovy-mk ros-groovy-nav-msgs ros-groovy-nodelet ros-groovy-nodelet-core ros-groovy-nodelet-topic-tools ros-groovy-orocos-kdl ros-groovy-pcl-msgs ros-groovy-physics-ode
  ros-groovy-pluginlib ros-groovy-polled-camera ros-groovy-qt-dotgraph ros-groovy-qt-gui-app ros-groovy-qt-gui-core ros-groovy-qt-gui-cpp ros-groovy-qt-gui-py-common
  ros-groovy-resource-retriever ros-groovy-robot-model ros-groovy-robot-model-tutorials ros-groovy-robot-model-visualization ros-groovy-robot-state-publisher ros-groovy-ros
  ros-groovy-ros-comm ros-groovy-ros-tutorials ros-groovy-rosbag ros-groovy-rosbash ros-groovy-rosboost-cfg ros-groovy-rosbuild ros-groovy-rosclean ros-groovy-rosconsole-bridge
  ros-groovy-roscpp-tutorials ros-groovy-roscreate ros-groovy-roslaunch ros-groovy-rosmake ros-groovy-rosmaster ros-groovy-rosmsg ros-groovy-rosnode ros-groovy-rosout ros-groovy-rosparam
  ros-groovy-rospy-tutorials ros-groovy-rosservice ros-groovy-rostest ros-groovy-rostopic ros-groovy-rosunit ros-groovy-roswtf ros-groovy-rqt-action ros-groovy-rqt-bag
  ros-groovy-rqt-bag-plugins ros-groovy-rqt-console ros-groovy-rqt-dep ros-groovy-rqt-graph ros-groovy-rqt-gui-cpp ros-groovy-rqt-launch ros-groovy-rqt-logger-level ros-groovy-rqt-moveit
  ros-groovy-rqt-msg ros-groovy-rqt-nav-view ros-groovy-rqt-plot ros-groovy-rqt-pose-view ros-groovy-rqt-publisher ros-groovy-rqt-py-common ros-groovy-rqt-py-console
  ros-groovy-rqt-reconfigure ros-groovy-rqt-robot-dashboard ros-groovy-rqt-robot-monitor ros-groovy-rqt-robot-steering ros-groovy-rqt-runtime-monitor ros-groovy-rqt-service-caller
  ros-groovy-rqt-shell ros-groovy-rqt-srv ros-groovy-rqt-tf-tree ros-groovy-rqt-topic ros-groovy-rqt-web ros-groovy-self-test ros-groovy-shape-msgs ros-groovy-smclib ros-groovy-srdf
  ros-groovy-srdfdom ros-groovy-stage ros-groovy-stereo-msgs ros-groovy-tf ros-groovy-tf-conversions ros-groovy-tf2 ros-groovy-tf2-geometry-msgs ros-groovy-tf2-kdl ros-groovy-tf2-msgs
  ros-groovy-tf2-ros ros-groovy-tf2-tools ros-groovy-timestamp-tools ros-groovy-topic-tools ros-groovy-trajectory-msgs ros-groovy-turtlesim ros-groovy-urdf ros-groovy-urdf-interface
  ros-groovy-urdf-parser ros-groovy-urdfdom ros-groovy-urdfdom-headers ros-groovy-visualization-msgs ros-groovy-xacro sphinx-common sphinx-doc tcl8.5-dev tk8.5-dev x11proto-composite-dev
  x11proto-randr-dev x11proto-render-dev x11proto-scrnsaver-dev x11proto-xinerama-dev
Use 'apt-get autoremove' to remove them.
The following extra packages will be installed:
  libavutil-extra-51
The following packages will be REMOVED:
  libavcodec-dev libavcodec53 libavformat-dev libavutil-dev libavutil51 libswscale-dev ros-groovy-opencv2
The following NEW packages will be installed:
  libavcodec-extra-53 libavutil-extra-51
0 upgraded, 2 newly installed, 7 to remove and 1 not upgraded.
Need to get 0 B/3,141 kB of archives.
After this operation, 53.2 MB disk space will be freed.
Do you want to continue [Y/n]?

**Comment by vrabaud** [comment]
ok, please make sure your packages are up to date (you have at least one that needs to be updated).
Also, please give us the output of dpkg -l libavcodec-extra-53

**Comment by juki21c** [comment]
My packages are up to date, and

$ dpkg -l libavcodec-extra-53
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
rc  libavcodec-extra-53:amd64                 6:0.8.6ubuntu0.12.10.1    amd64                     Libav codec library

**Comment by vrabaud** [comment]
ok, the error is obvious no ? You have some quantal packages (somehow) as you have 12.10. The version I get is : 4:0.8.6ubuntu0.12.04.1
So make sure you do not have any weird ppa around or use aptitude to use the proper version.
The error you get has nothing to do with the fact that it's extra or not. It's all about the version number.

**Comment by juki21c** [comment]
My Ubuntu version is 12.10 64-bit. By any chance, does ros-groovy-opencv2 only support Ubuntu 12.04?

The image attached shows the software source list.

![screenshot from 2013-09-04 20 07 57](https://f.cloud.github.com/assets/675388/1085035/62e9bfa8-15bf-11e3-9d1c-ab98934c107e.png)

**Comment by vrabaud** [comment]
aaaah, my bad, I kept reading Precise ..... So your package version is normal. Now that we are dropping Fuerte, I will upgrade to Quantal.
Still that works for me on Precise with Groovy and Raring and Hydro, it's a standard Ubuntu behavior.
ros-groovy-opencv2 definitely supports all the Ubuntu releases supported by ROS so groovy is fine.

**Comment by vrabaud** [comment]
ok, your bug is actually an upstream bug:
https://bugs.launchpad.net/ubuntu/+source/libav/+bug/1038781
I cannot have ros-groovy-opencv2 depend on the *extra as this is not the proper Ubuntu behavior and could break other packages depending on the non-extra. What I did (which is ugly) under Quantal was to change quantal to raring in /etc/apt/source.list, sudo apt-get update, and then only install the packages you need (libavcodec-extra-53 libavcodec-dev libavformat-extra-53 libavformat-dev libswscale-extra-2 libswscale-dev  libavutil-extra-51 libavutil-dev). Then you convert raring back to quantal in the file and you're good to go. That worked for me
Or you switch to Hydro and raring as the fix is there :)
