### ISSUE TITLE
opencv3 build issue

### ISSUE THREAD

**Issue by doll6777** [ros-perception/vision_opencv#224]
****

I encoountered error. I installed opencv3 3.4.1 and checked It is not muti-installed with opencv 2.4.1
I think when i am trying to build, it reads opencv3 file but try to build with opencv2. 
can i know the reason?

                                                                                  ^
/home/user/ros2_ws/src/vision_opencv/cv_bridge/src/module_opencv3.cpp:206:32: error: expected ‘(’ before ‘)’ token
     size[i] = (static_cast<int>)_sizes[i];
                                ^
/home/user/ros2_ws/src/vision_opencv/cv_bridge/src/module_opencv3.cpp:206:32: error: expected primary-expression before ‘)’ token
/home/user/ros2_ws/src/vision_opencv/cv_bridge/src/module_opencv3.cpp:206:33: error: expected ‘)’ before ‘_sizes’
     size[i] = (static_cast<int>)_sizes[i];
                                 ^
/home/user/ros2_ws/src/vision_opencv/cv_bridge/src/module_opencv3.cpp:232:82: error: reinterpret_cast from type ‘const PyObject* {aka const _object*}’ to type ‘PyArrayObject* {aka tagPyArrayObject*}’ casts away qualifiers
  = cv::Mat(ndims, size, type, PyArray_DATA(reinterpret_cast<PyArrayObject *>(o)), step);
                                                                               ^
/home/user/ros2_ws/src/vision_opencv/cv_bridge/src/module_opencv3.cpp:235:7: error: ‘class cv::Mat’ has no member named ‘refcount’
     m.refcount = refcountFromPyObject(o);
       ^

**Comment by gaoethan** [comment]
Sorry, I don't see it directs to the opencv2 from the log ?  I advised that you only install opencv3 with a clear   environment to double check,  thanks !

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue has not been active for a while, I'm going to close it due to inactivity. Please feel free to comment if it is still relevant and you would like to get it re-opened.
