### ISSUE TITLE
Cmake config problem in cv_bridge on kinetic armhf? 

### ISSUE THREAD

**Issue by felixendres** [ros-perception/vision_opencv#234]
I build a ROS package for indigo and kinetic on armhf and amd64. The only failure I get is for kinetic on armhf:

> -- Found OpenCV: /opt/ros/kinetic (found suitable version "3.3.1", minimum required is "3") found components:  core highgui imgproc imgcodecs 
> CMake Error at /opt/ros/kinetic/share/cv_bridge/cmake/cv_bridgeConfig.cmake:113 (message):
>   Project 'cv_bridge' specifies '/opt/ros/kinetic/include/opencv-3.3.1' as an
>   include dir, which is not found.  It does neither exist as an absolute
>   directory nor in '/opt/ros/kinetic//opt/ros/kinetic/include/opencv-3.3.1'.

I checked the ros-kinetic-opencv3 package and its headers are in 
/opt/ros/kinetic/include/opencv-3.3.1-dev/ so probably it's just the -dev that's missing.

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue is raised against a distro that has reached EOL, I'm going to close it out. Please feel free to comment if it is still relevant and you would like to get it re-opened.
