### ISSUE TITLE
hydro support

### ISSUE THREAD

**Issue by dawonn** [ros-perception/vision_opencv#24]
Will there be a hydro-devel branch?

**Comment by vrabaud** [comment]
probably not. No new features are planned. So for hydro, you now use the groovy-devel branch. I could rename that to master.

**Comment by vrabaud** [comment]
is there a reason for such a branch or should I close that bug ? Even catkin did not create one: https://github.com/ros/catkin
No need if no API is broken.

**Comment by dawonn** [comment]
Ah, I see now. I suppose there isn't any reason for it, I was just confused by the lack of hydro-devel initially. :P
