### ISSUE TITLE
Python support for numpy based cv2 API

### ISSUE THREAD

**Issue by LucidOne** [ros-perception/vision_opencv#26]
Using the cv2 API in Python requires 

```
image_mat = self.bridge.imgmsg_to_cv(data, "bgr8")
image_numpy = numpy.asarray(image_mat)
```

Maybe it is just undocumented but it looks like we need support for the cv2 API in Python.
http://opencv-users.1802565.n2.nabble.com/Python-user-wonders-why-cv-and-cv2-td6985196.html

**Comment by vrabaud** [comment]
The cv API is to the cv2 API what C and C++ are (very roughyl). The cv API will be deprecated in OpenCV 3.0.
All the tutorials consider cv2:
http://docs.opencv.org/trunk/doc/py_tutorials/py_tutorials.html
(yes, there are many tutorials in trunk ! :) )
For what you mention, the easiest is probably to create a bridge.imgmsg_to_cv2  function. Do you agree with that decision ?

**Comment by LucidOne** [comment]
Awesome, Thanks!

**Comment by vrabaud** [comment]
@LucidOne  can you please confirm that this works for you ? (I created heavy tests for it but I did not try it in a real setup). Thx.

**Comment by vrabaud** [comment]
@LucidOne  , that works for you ? (I want to know whether I can release it)

**Comment by LucidOne** [comment]
Works great!

**Comment by LucidOne** [comment]
```
class mynode:

  def __init__(self):
    if ('imgmsg_to_cv2' in CvBridge.__dict__):
      self.imgmsg_to_cv2 = self.bridge.imgmsg_to_cv2
    else:
      self.imgmsg_to_cv2 = self.imgmsg_to_np

  def imgmsg_to_np(self,data,encoding):
    return np.asarray(self.bridge.imgmsg_to_cv(data,encoding))
```

**Comment by vrabaud** [comment]
cool ! finally released it.
