### ISSUE TITLE
change *.h to *.hpp in ros2 branch

### ISSUE THREAD

**Issue by xhuan28** [ros-perception/vision_opencv#262]
According to the [migration guide](https://index.ros.org/doc/ros2/Migration-Guide/), the suffix of header files should be changed from *.h to *.hpp, but I notice that the the suffixes are still *.h in ros2 branch.

**Comment by threeal** [comment]
Will this issue going to be resolved? as i think renaming the header files will create a problem on other packages that depends on this package.

**Comment by ijnek** [comment]
All .h files have been deprecated in I-turtle, and have removed for J-turtle onwards!
