### ISSUE TITLE
Image Message step handling broken

### ISSUE THREAD

**Issue by jensenb** [ros-perception/vision_opencv#27]
The cv_bridge handling of the image step size field of an image message is broken. Introduced in ee10a9dc9fd20145d04c47e8c2fe50a8a6f4c3a1 there is now an invariant when converting ROS Image Messages to `cv::Mat` instances where the step size has to be equal to the image element size \* the number  of channels \* the image width. If this invariant is not fulfilled an exception is thrown, crashing rqt_image_view for example. This is requirement is not listed on the wiki page, and is not listed in the Image Message documentation: http://docs.ros.org/api/sensor_msgs/html/msg/Image.html. Aligned Image Messages are thus no longer supported.

I see no reason why the cv_bridge step handling has to forbid aligned images, when the underlying OpenCV API has no problem with this.

**Comment by jensenb** [comment]
I can submit a pull request if that would help

**Comment by vrabaud** [comment]
I will have time in a few hours (3/4). The pull request is more than welcome but please, also add a test for it.

**Comment by vrabaud** [comment]
that got fixed in #28
