### ISSUE TITLE
imgmsg_to_cv2 return numpy.ndarray

### ISSUE THREAD

**Issue by eraserpencil** [ros-perception/vision_opencv#282]
When I'm trying some stuff with a codebase that previously uses [cv_bridge](http://wiki.ros.org/cv_bridge/Tutorials/ConvertingBetweenROSImagesAndOpenCVImagesPython#ROS-Kinetic_Compatibility). Imgmsg_tocv2 always returned a cv::Mat. But after testing around with some python3 codebase and changing some dependencies, Imgmsg_to_cv2 now returns numpy.ndarray.

I am on Ubuntu 16.04, currently running python 2.7.12, opencv version 3.4.1, ROS Kinetic

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue is aganist a distro that has reached EOL, I'm going to close it. Please feel free to comment if it is still relevant and you would like to get it re-opened.
