### ISSUE TITLE
Invoking "make cmake_check_build_system" failed

### ISSUE THREAD

**Issue by Algabri** [ros-perception/vision_opencv#297]
I am using the OpenCV4Tegra with Jetson TX2
the system:

 NVIDIA Jetson TX2
 L4T 28.2.1 [ JetPack 3.3 or 3.2.1 ]
 Board: t186ref
 Ubuntu 16.04.6 LTS
 Kernel Version: 4.4.38-tegra
 CUDA 9.0.252

the error:
`-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
CMake Error at vision_opencv/cv_bridge/CMakeLists.txt:16 (find_package):
  Could not find a package configuration file provided by "OpenCV" (requested
  version 3) with any of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/nvidia/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/nvidia/catkin_ws/build/CMakeFiles/CMakeError.log".
Makefile:318: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
`

I used your method on my PC with GPU 1050 is very very nice.

I get some solutions [here]( https://devtalk.nvidia.com/default/topic/1008011/jetson-tx1/opencv-3-2-0-cmakelists-txt-question/) but it seems that he built OpenCV  not OpenCV4Tegra

PS. help me or any suggestion??

**Comment by ijnek** [comment]
I recently became the maintainer of this repo, and I'm sorting through issues, closing stale ones. As this issue has not been active for a while, I'm going to close it due to inactivity. Please feel free to comment if it is still relevant and you would like to get it re-opened.
