### ISSUE TITLE
'/usr/include/opencv'  not found!

### ISSUE THREAD

**Issue by JeyP4** [ros-perception/vision_opencv#316]
Hi
My system is Jetson Nano ubuntu 18.04. Ros-melodic.
Jetson came with opencv 4.1.1. And during ROS installation, it did not install opencv3.
But Seperately, I source build opencv3.4.0. So now I have two opencvs.

![image](https://user-images.githubusercontent.com/44414900/74539411-473d7c80-4f3e-11ea-9437-4e0ebb7b9e4d.png)

To solve above problem, I tried to modify `/opt/ros/melodic/lib/pkgconfig/cv_bridge.pc`. Here I edited include and libs pointing opencv3.4.0.
How can I recompile cv_bridge to make the changes effective.

My `/usr/include` looks like this:
![image](https://user-images.githubusercontent.com/44414900/74539736-d64a9480-4f3e-11ea-9037-edb4fd21c14f.png)

**Comment by JeyP4** [comment]
`sudo apt purge ros-melodic-cv-bridge`
`cd catkin_ws/`
`git clone https://github.com/ros-perception/vision_opencv.git`

ensure `pkg-config --modversion opencv` able to find OPENCV3.4.0

`catkin_make -DCMAKE_BUILD_TYPE=Release`

**Comment by henryfhq** [comment]
@JeyP4  Hi

I also encounter the same issue as you and I tried to run the solution as mentioned above. However, the issue still persist. Here is the picture:

![Screenshot from 2020-05-14 17-39-31](https://user-images.githubusercontent.com/64243957/81919046-e3445600-9609-11ea-98fe-dc8348333185.png)

So is there a way that I can resolve it?
I am using the Jetson Nano and I'm using Ubuntu 18.04 and ROS version is melodic.

Thank you very much.

**Comment by phoenixrider12** [comment]
Hey @JeyP4 
how did you install opencv 3.4?
