### ISSUE TITLE
Python imgmsg_to_cv2 memory leak

### ISSUE THREAD

**Issue by cburbridge** [ros-perception/vision_opencv#34]
When using the `imgmsg_to_cv2` function from Python `cv_bridge.CvBridge` class, memory is leaked if colour conversion is performed. I am using the latest Hydro release, code like this:

``` python
    def image_cb(self, image):
            try:
                ## This leaks, using colour conversion:
                #self._image = self.bridge.imgmsg_to_cv2(image, "bgr8")
                ## This works, no conversions:
                self._image = self.bridge.imgmsg_to_cv2(image)
            except CvBridgeError, e:
                print e

```

Looking at the refcounts for self._image.block, they are screwed up when using colour conversion and fine otherwise. Am I just missing something?

**Comment by vrabaud** [comment]
Hi, can you please confirm that this patch works ? thx

**Comment by cburbridge** [comment]
Yep, fixed, and incredibly fast :-) Thanks.

**Comment by vrabaud** [comment]
cool ! Releasing for all releases then. Memory leaks need to be fixed fast :)
