### ISSUE TITLE
1.10.16 groovy and hydro has wrong changelogs

### ISSUE THREAD

**Issue by tfoote** [ros-perception/vision_opencv#35]
This is causing invalid debians to build and the buildfarm to infinite loop

https://github.com/ros/rosdistro/pull/3926

**Comment by tfoote** [comment]
Example https://github.com/ros-gbp/vision_opencv-release/blob/debian/ros-hydro-image-geometry_1.10.16-0_precise/debian/changelog

**Comment by tfoote** [comment]
This was causing infinite triggering: http://jenkins.ros.org/job/ros-groovy-image-geometry_sourcedeb/

**Comment by vrabaud** [comment]
that was fixed in 2447b702d11cf441ce5a90f424fac052ce407d4b, thx
