### ISSUE TITLE
rosco vision_opencv pulls from SVN

### ISSUE THREAD

**Issue by ahendrix** [ros-perception/vision_opencv#4]
When I do 'rosco vision_opencv' to get the source for opencv, it pulls from SVN.

**Comment by ahendrix** [comment]
This looks like it's a result of roslocate producing the wrong result:

$ roslocate info vision_opencv
- svn:
  local-name: vision_opencv
  uri: https://code.ros.org/svn/ros-pkg/stacks/vision_opencv/trunk

**Comment by vrabaud** [comment]
roslocate pulls info from the wiki, from the default page of the package (Fuerte right now).

**Comment by vrabaud** [comment]
ok, just got fixed with the new docs/branches
