### ISSUE TITLE
proposal for adding visoin_examples repository

### ISSUE THREAD

**Issue by k-okada** [ros-perception/vision_opencv#40]
I'd like to propose new repository, that contains ros node for opencv examples, such as face detection, edge detection, template matching, optical flows....(https://github.com/Itseez/opencv/tree/master/samples/cpp)

The motivation is 
1) every one who learn  vision based robotic behavior, they start from red-ball tracking or face recognition, but currently there are no collection of such simple vision processing example so that every one have to write their own code
2) when I explain (advertise, push) ROS to other people, I'll explain "there are great collection of useful software modules and it is super easy to use them". and if we can run face detection example with just few seconds and the same software can run on different camera (usb cam vs kinect), then that will support my opinion.

here is the some list of existing vision node:
- face detection : http://sourceforge.net/p/tum-ros-pkg/code/HEAD/tree/perception/face_detector_mono/
- template match: http://sourceforge.net/p/tum-ros-pkg/code/HEAD/tree/perception/fast_match_template/
- cmvision(color segmentaiton), hsv filter, circle 2d, lk tracker, http://sourceforge.net/p/tum-ros-pkg/code/HEAD/tree/perception/image_algos/src/
- checker_board : https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/checkerboard_detector, http://robotics.usc.edu/ros/category/stacks/oit?q=content/checkerboard, https://github.com/uscrs-art/beohawk-ros/blob/master/art_vision/src/checkerboard.cpp
- optical flow: https://github.com/uscrs-art/beohawk-ros/blob/master/art_vision/src/optical_flow.cpp

**Comment by vrabaud** [comment]
Solved in #56  thx to @k-okada !
