### ISSUE TITLE
bad build in ros-hydro-opencv2?

### ISSUE THREAD

**Issue by bricerebsamen** [ros-perception/vision_opencv#41]
hello

Some of the code I'm maintaining that uses cv::HOGDescriptor started to crash after the recent release of ros-hydro-opencv2 (Jun 17). I checked on https://github.com/ros-gbp/opencv2-release.git and apparently it's still the same version 2.4.9, since last fall. So is there an explanation for this problem? 

I'm 99.9% sure it's not on my side, as I tested with old version of my code that I know was working some weeks ago.

Brice

**Comment by bricerebsamen** [comment]
digging a bit more, it appears that this package was recently upgraded from 2.4.6 to 2.4.9 which is probably the cause of my problem. I'll see with the opencv community.

**Comment by vrabaud** [comment]
Yes, please, file a bug report at http://code.opencv.org/projects/opencv/issues if it is on the OpenCV side. Then, come back to here where I'll release a new version with the patch.

**Comment by vrabaud** [comment]
sorry for the inconvenience but there were other important fixes in 2.4.9. I'll patch it whenever you can figure out what is happening, thx.
