### ISSUE TITLE
Foxy toImageMsg() should return a std::unique_ptr?

### ISSUE THREAD

**Issue by KenYN** [ros-perception/vision_opencv#413]
Since `publish()` now takes `std::unique_ptr` or a plain `sensor_msg::msg::Image`, we lose zero copy benefits. Is it possible to return a `std::unique_ptr` from `toImageMsg()` on Foxy, or some other way to guarantee zero copy.

**Comment by 1hao-Liu** [comment]
@KenYN Have you solved this problem? I also had this problem when I wanted to send image from cv::mat format to sensor_msgs::msg::Image in ROS2 Galactic. Thank you!

**Comment by ZhenshengLee** [comment]
> we lose zero copy benefits

I think the zero copy benefits of unique_ptr is only involved in rclcpp-intra-process context, 

For intra-process-comm in Humble, type_adaption feature could be used to get better performance.

For galactic and foxy, is there any plan to return a std::unique_ptr? @ijnek 

Thanks.

**Comment by ijnek** [comment]
> For intra-process-comm in Humble, type_adaption feature could be used to get better performance.

I agree with this.

> For galactic and foxy, is there any plan to return a std::unique_ptr?

There are no plans on adding features in distros that have already been released, only bug fixes are backported. Note that this applies to the Type Adapter feature added in https://github.com/ros-perception/vision_opencv/pull/441, this is only available on the rolling branch.

**Comment by ijnek** [comment]
In regards to the original issue, I would be happy to review a PR incorporating the changes suggested.

**Comment by ZhenshengLee** [comment]
@KenYN

> Since publish() now takes std::unique_ptr or a plain sensor_msg::msg::Image, we lose zero copy benefits.

I think it's not true after reading the code in rclcpp.

for humble, when use ros-type-msg

https://github.com/ros2/rclcpp/blob/7f575103d8fe06285bd46474a0324c7dfbb2a2f0/rclcpp/include/rclcpp/publisher.hpp#L287-L304

```cpp
  template<typename T>
  typename std::enable_if_t<
    rosidl_generator_traits::is_message<T>::value &&
    std::is_same<T, ROSMessageType>::value
  >
  publish(const T & msg)
  {
    // Avoid allocating when not using intra process.
    if (!intra_process_is_enabled_) {
      // In this case we're not using intra process.
      return this->do_inter_process_publish(msg);
    }
    // Otherwise we have to allocate memory in a unique_ptr and pass it along.
    // As the message is not const, a copy should be made.
    // A shared_ptr<const MessageT> could also be constructed here.
    auto unique_msg = this->duplicate_ros_message_as_unique_ptr(msg);
    this->publish(std::move(unique_msg));
  }
```

from the code in rclcpp, we can use this to get zero-copy during intra-processing-comm, but the copy during type-conversion(in cv_bridge::toImageMsg, there is a memcpy)

```cpp
m_input_cvimage->header.stamp = now();
auto msg = std::make_shared<Topic>();\
// a copy in type-conversion
m_input_cvimage->toImageMsg(*msg);
// no copy during intra-processe because rclcpp will help us to send unique_ptr
m_publisher->publish(std::move(*msg));
```

the subscriber should like this

```cpp
auto callback = [this](const Topic::SharedPtr msg) -> void {

      RCLCPP_INFO(this->get_logger(), "Received...");
      // there's no copy in type-conversion, but we lose the write permission to the image.
      m_last_cvimage = cv_bridge::toCvShare(msg);
}
```

@ijnek  what do you think?

Thanks.

**Comment by ijnek** [comment]
@ZhenshengLee Sorry for the delay in the reply.

Copy does happen inside cv_bridge due to memcpy, but as long as a subscription is made with: 

```cpp
auto callback = [this](const Topic::ConstSharedPtr msg) -> void
```

the subscriber should be able to get a read-only copy of the message, with zero intraprocess copies.

I believe using ``ConstSharedPtr`` is necessary, and ``SharedPtr`` is not enough. (From [ROS2 design](https://design.ros2.org/articles/intraprocess_communications.html))

@ZhenshengLee Are you suggesting a change somewhere, or are you fine with me closing this issue?

**Comment by ZhenshengLee** [comment]
@ijnek I think it's ok to close this issue.

**Comment by ijnek** [comment]
Thanks @ZhenshengLee , I'm going to go ahead and close this.
