### ISSUE TITLE
Include missing in ROS 2 branch

### ISSUE THREAD

**Issue by sgoulli** [ros-perception/vision_opencv#425]
Hi @mjcarroll, I noticed that the file cv_bridge_export.h is missing in the ROS2 branch.

**Comment by clydemcqueen** [comment]
cv_bridge_export.h is generated by cv_bridge/src/CMakeLists.txt. This PR gives the background: https://github.com/ros-perception/vision_opencv/pull/301

**Comment by ijnek** [comment]
Closing, as the previous comment explains the issue.
