### ISSUE TITLE
Getting an error with getConversionCode and SAME_FORMAT

### ISSUE THREAD

**Issue by JohnVorwald** [ros-perception/vision_opencv#432]
Hello,
   I'm getting errors trying to build the package 

https://github.com/maciejmatuszak/ros_gpu_stereo_processor/tree/master/src

Here are the error message

error: ‘getConversionCode’ is not a member of ‘cv_bridge’
         const std::vector<int> conversion_codes = cv_bridge::getConversionCode(src_encoding, dst_encoding);

error: ‘SAME_FORMAT’ is not a member of ‘cv_bridge’
         if (conversion_code == cv_bridge::SAME_FORMAT)

I tried uninstalling and reinstalling cv_bridge, but same result

sudo apt-get remove --auto-remove ros-melodic-cv-bridge 
sudo apt-get install ros-melodic-cv-bridge
sudo apt-get install ros-melodic-stereo-msgs 
sudo apt-get install ros-melodic-ddynamic-reconfigure
catkin_make --pkg gpuimageproc

Here is where cv_bridge is located

catkin_find cv_bridge
/opt/ros/melodic/include/cv_bridge
/opt/ros/melodic/share/cv_bridge

Here is debug output from CMakeList.txt

-- ROS_GPU_STEREO_PROCESSOR OpenCV_INCLUDE_DIRS: 
-- CMakeList Project ros_gpu_stereo_processor:
--   OpenCV library status:
--     OpenCV version: 3.2.0
--     OpenCV libraries: 
--     OpenCV include path: 
-- CMakeList Project ros_gpu_stereo_processor:
--   cv_bridge library status:
--     cv_bridge version: 1.13.0
--     cv_bridge libraries: 
--     cv_bridge include path: /opt/ros/melodic/include/usr/include/usr/include/opencv

**Comment by ijnek** [comment]
The repository you pointed to seems to be relying on a modified version of vision_opencv (without telling you), and you're trying to use the non-modified official version of vision_opencv, and the differences are causing the error.

As there is nothing to fix in this repository, I'm going to close this off. Please get in touch with maciejmatuszak to figure out where his modified branch is, perhaps you can find his fork in his github account.
