### ISSUE TITLE
CMake Error ! Not able to execute catkin_make. Have updated the CMakeLists.txt file but still it isnt working.

### ISSUE THREAD

**Issue by anandbharadwaj1** [ros-perception/vision_opencv#436]
catkin_make
Base path: /home/airl010/catkin_1
Source space: /home/airl010/catkin_1/src
Build space: /home/airl010/catkin_1/build
Devel space: /home/airl010/catkin_1/devel
Install space: /home/airl010/catkin_1/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/airl010/catkin_1/devel
-- Using CMAKE_PREFIX_PATH: /home/airl010/catkin_1/devel;/home/airl010/catkin_ws/devel;/opt/ros/melodic
-- This workspace overlays: /home/airl010/catkin_1/devel;/home/airl010/catkin_ws/devel;/opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/airl010/catkin_1/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 18 packages in topological order:
-- ~~  - zed_ar_track_alvar_example
-- ~~  - zed_cam
-- ~~  - zed_depth_sub_tutorial
-- ~~  - zed_display_rviz
-- ~~  - zed_examples (metapackage)
-- ~~  - zed_interfaces
-- ~~  - rviz_plugin_zed_od
-- ~~  - zed_multicamera_example
-- ~~  - zed_nodelet_example
-- ~~  - zed_nodelets
-- ~~  - zed_obj_det_sub_tutorial
-- ~~  - zed_ros (metapackage)
-- ~~  - zed_rtabmap_example
-- ~~  - zed_sensors_sub_tutorial
-- ~~  - zed_sync_test
-- ~~  - zed_tracking_sub_tutorial
-- ~~  - zed_video_sub_tutorial
-- ~~  - zed_wrapper
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'zed_ar_track_alvar_example'
-- ==> add_subdirectory(zed-ros-examples/examples/zed_ar_track_alvar_example)
-- +++ processing catkin package: 'zed_cam'
-- ==> add_subdirectory(zed_cam)
-- Could NOT find opencv2 (missing: opencv2_DIR)
-- Could not find the required component 'opencv2'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "opencv2" with any
  of the following names:

    opencv2Config.cmake
    opencv2-config.cmake

  Add the installation prefix of "opencv2" to CMAKE_PREFIX_PATH or set
  "opencv2_DIR" to a directory containing one of the above files.  If
  "opencv2" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  zed_cam/CMakeLists.txt:10 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/airl010/catkin_1/build/CMakeFiles/CMakeOutput.log".
See also "/home/airl010/catkin_1/build/CMakeFiles/CMakeError.log".
Makefile:2579: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
[CMakeLists.txt](https://github.com/ros-perception/vision_opencv/files/8812515/CMakeLists.txt)

**Comment by ijnek** [comment]
Hi @anandbharadwaj1, this seems like a question, and is more suited to [ROS Answers](https://answers.ros.org/questions/).
From the log you've posted, the issue seems to be in the zed_cam repository (I'm not sure where you got it from) and unrelated to this repository.
I'm going to close this off. If you're looking for debugging guidance, please post on ROS Answers, and once you've found the issue, please raise an issue against the appropriate repository. Thanks!
