### ISSUE TITLE
broken dependencies?

### ISSUE THREAD

**Issue by bricerebsamen** [ros-perception/vision_opencv#44]
My colleague messed up his system, and so we had to reinstall ROS, and rebuild the workspace. We ran into an interesting issue that I believe is worth reporting.

Although he had installed `image_proc`, and `vision_opencv`, etc. (we tried a lot of stuffs to get it to work), it had not installed `ros-hydro-opencv2`... It was instead compiling against the `libopencv` deb. As a result it was complaining that there was no rule for target `/opt/ros/hydro/lib/opencv_videostab.so.2.4.9` (from memory). 

Installing ros-hydro-opencv2 fixed the problem, but I was surprised that it was not installed directly from installing image_proc and friends.

**Comment by vrabaud** [comment]
to clarify:
- you are on Hydro
- you installed image_proc and vision_opencv from deb from the debs in the ppa at http://packages.ros.org/ros/ubuntu  (not http://packages.ros.org/ros-shadow-fixed/ubuntu)

both vision_opencv and image_proc depend on cv_bridge (which depends on opencv2):
https://github.com/ros-perception/image_pipeline/blob/hydro-devel/image_proc/package.xml#L31
https://github.com/ros-perception/vision_opencv/blob/groovy-devel/vision_opencv/package.xml#L17
https://github.com/ros-perception/vision_opencv/blob/groovy-devel/cv_bridge/package.xml#L28

My guess is that you had a problem with your packages in the first place (messed up system). 

If such an error existed, the build farm would simply fail so I am closing this one (sorry, no futher details you provide could explain the error).
