### ISSUE TITLE
Change default branch to ``rolling``

### ISSUE THREAD

**Issue by ijnek** [ros-perception/vision_opencv#453]
In the ROS 2 Core libraries, the default branch was modified: [Change default branch name to ‘rolling’ in ROS 2 core](https://discourse.ros.org/t/change-default-branch-name-to-rolling-in-ros-2-core/26009)

I think we should do the same here, and:
- [ ] Create a ``rolling`` branch.
- [ ] Add the GitHub action to automatically sync between the new ``rolling`` branch and the old ros2 branch.
- [ ] Update the default branch from ``noetic`` to ``rolling``.
- [ ] Retarget existing PRs that target the ``ros2`` branch to target the ``rolling`` branch.

**Comment by ijnek** [comment]
I don't have permission to rename branches or to change the default branch. Would you be able to either give me additional rights to do this, or do this for me? @clalancette

**Comment by clalancette** [comment]
I just upgraded your rights to "Maintain", which I think should be enough to do that.

**Comment by ijnek** [comment]
Thanks @clalancette

**Comment by ijnek** [comment]
I've renamed ``ros2`` branch to ``rolling``

**Comment by ijnek** [comment]
> People with admin permissions to a repository can change the default branch for the repository.

(https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch)

@clalancette It seems like I need admin access :(. Alternatively, it should be a one-off thing so you could just change the default branch and that should be fine.

**Comment by clalancette** [comment]
> @clalancette It seems like I need admin access :(. Alternatively, it should be a one-off thing so you could just change the default branch and that should be fine.

So just to be totally clear; this repository supports both ROS 1 (via  the `noetic` branches) and ROS 2 (now via the `rolling` branch).  Currently, the `noetic` branch is the default one.  I'll change it to `rolling` if that is what you want, but I wanted to make you aware that this is more than just a branch rename.

**Comment by ijnek** [comment]
Yes, I want the default branch to be retargeted from ``noetic`` to ``rolling``. Are there some obvious unintended side-effects that I should be aware of...?

**Comment by clalancette** [comment]
> Yes, I want the default branch to be retargeted from `noetic` to `rolling`. Are there some obvious unintended side-effects that I should be aware of...?

Just that any new PRs targeting ROS 1 will have to manually target `noetic`.  We haven't done this on many of the repositories that are shared between ROS 1 and ROS 2, but that doesn't mean we can't.  I just wanted to make sure that was your intention.

I'll go ahead and make the change.

**Comment by clalancette** [comment]
It's done now.

Keep in mind that to make this totally work correctly, you'll also have to update https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml to point to the correct branch, as well as https://github.com/ros2-gbp/vision_opencv-release/blob/master/tracks.yaml#L238

**Comment by ijnek** [comment]
Thanks! rosdistro has been updated in https://github.com/ros/rosdistro/pull/34463, and I've changed tracks.yaml in https://github.com/ros2-gbp/vision_opencv-release/commit/a9c882edc18e28ce8a86980253c519b8864e49a8
