### ISSUE TITLE
missing numpy dependency in package.xml

### ISSUE THREAD

**Issue by tkruse** [ros-perception/vision_opencv#47]
It seems cv_bridge/src/CmakeLists.txt needs numpy, but it is not declared in package.xml.
The package missing in ubuntu was python-numpy-dev, if that helps.

**Comment by tkruse** [comment]
seems my virtualenv was missing it. So not sure now about whether -dev is required.

**Comment by vrabaud** [comment]
hmm, cv_bridge depends on python-opencv which depends on python-numpy. That's on Ubuntu but that should be the case on other distros. Tests would fail if it did not depend on it.

**Comment by tkruse** [comment]
ok, as I said my virtualenv was messed up. So maybe not necessary, feel free to close

**Comment by bchretien** [comment]
Actually, on Arch the Python bindings are part of the [`opencv`](https://www.archlinux.org/packages/extra/x86_64/opencv/) package, and NumPy is an optional dependency. It seems to be the only distribution with this organization, so if you think that modifying `packages.xml` is not the way to go, I guess I can make a PR to rosdistro and add NumPy [there](https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L755).

**Comment by vrabaud** [comment]
thx
