### ISSUE TITLE
wiki tutorials out of date

### ISSUE THREAD

**Issue by wjwwood** [ros-perception/vision_opencv#48]
I went through and updated a few of the pages to include catkin specific instructions, but the examples are using obsolete API's, for example on this page:

http://wiki.ros.org/image_transport/Tutorials/PublishingImages

@vrabaud is there any chance you could look at those and at least tell me how they should change?

**Comment by wjwwood** [comment]
As a follow up, this page:

http://wiki.ros.org/image_transport/Tutorials/ManagingPlugins

Details how to use the `list_transports` program which comes with `image_transport`. This program recommends the user build packages which is seems to detect are not built, but do provide plugins. I think it needs to be touched up and this wiki page then updated.

**Comment by vrabaud** [comment]
finally done with that one ! Thx for pointing that out.
