### ISSUE TITLE
``foxy`` and ``galactic`` branch contains breaking changes since last release

### ISSUE THREAD

**Issue by ijnek** [ros-perception/vision_opencv#485]
When I branched off ``foxy``and ``galactic`` branches, I branched off from the ``ros2`` branch, because that was the dev branch listed in rosdistro for the distributions. However, the ``ros2`` branch contained a significant number of breaking changes, and the ``foxy``and ``galactic`` branches shouldn't have been branched off ``devel``.

Should try and revert all the breaking changes in the two branches to get the ``foxy``and ``galactic`` branches working and make a release.

**Comment by ijnek** [comment]
I've gone through all PRs that were merged since the last release in Foxy and Galactic.

Changes that need to be reverted:

- [ ] #419 
- [ ] #421
- [ ] #422

Changes that don't have to be reverted:

- [x] #352 
- [x] #356 
- [x] #370 
- [x] #392 
- [x] #397 
- [x] #396 
- [x] #399 
- [x] #357 
- [x] #400
- [x] #388 
- [x] #358
- [x] #359
- [x] #378
- [x] #417
- [x] #412
- [x] #326
- [x] #420
- [x] #423
- [x] #418
- [x] #427
- [x] #439
- [x] #252 
- [x] #444 
- [x] #451

**Comment by Ace314159** [comment]
Is there a reason to revert #421 and #422 as well? After the revert, builds do not work when using a Boost 1.67 or newer, as explained in https://github.com/ros-perception/vision_opencv/pull/390#issuecomment-839943369
> from [this document](https://cmake.org/cmake/help/latest/module/FindBoost.html):
> 
> > Note that Boost Python components require a Python version suffix (Boost 1.67 and later), e.g. python36 or python27 for the versions built against Python 3.6 and 2.7, respectively. This also applies to additional components using Python including mpi_python and numpy. Earlier Boost releases may use distribution-specific suffixes such as 2, 3 or 2.7. These may also be used as suffixes, but note that they are not portable.

**Comment by ijnek** [comment]
Hi @Ace314159, sorry for the inconvenience the reversion has caused and thanks for reporting it. Let's get it resolved.

Here's the original reasons:
#419 was reverted because that was the PR that was breaking API in foxy and galactic.
#421 was reverted because it depended a lot on changes from #419
#422 was reverted because it was fixing mistakes in #421.

However, now looking at #390, this is suggesting to me that the foxy/galactic build on windows might fail after the reversions I've made.

Could you describe the platform / distribution that's failing? And also, which branch you're building from source, (or whether you are using a binary).

**Comment by Ace314159** [comment]
Thanks for the prompt response! I am building from source using the foxy branch on Windows.

**Comment by ijnek** [comment]
Great, thanks for the information. Could you try out the branch: ``foxy-with-boost-python-fix`` I just put up?
It has changes from #390 applied, which was easier to port across than the changes from #421.

**Comment by Ace314159** [comment]
It works! Thanks for the quick turnaround!

**Comment by ijnek** [comment]
I'm going to re-open this issue until a release has been made. I'm currently trying to figure out how to get a pre-release test going before I make another release.

**Comment by ijnek** [comment]
Releases were made.

However, I've been reported that the backport to galactic broke Galactic builds on RHEL: https://build.ros2.org/job/Gbin_rhel_el864__cv_bridge__rhel_8_x86_64__binary/

I've reverted the release to an older version until we resolve this. Let's track this issue here.

**Comment by ijnek** [comment]
@Ace314159 could you review #495 please?

**Comment by Ace314159** [comment]
It looks good to me! Just wasn't sure about the `COMPONENTS` thing I mentioned.

**Comment by ijnek** [comment]
Closing, as should be fixed with #495 :crossed_fingers:
