### ISSUE TITLE
CvBridge not supporting no channel information (OpenCV at fault)

### ISSUE THREAD

**Issue by NumesSanguis** [ros-perception/vision_opencv#49]
I don't know how much the error is because of CvBridge, but I have some problem with sending gray images over ROS, see:
https://stackoverflow.com/questions/26610235/ros-cvbridge-not-working-because-of-channel-information

The problem lays in that using functions like cv2.resize() when used on a gray image (x, y, channel=1) loses the channel information. Color images work perfectly fine because the channel information (3 channels) is not lost. Would it be possible to send gray images without channel information with CvBridge, do you know a way to not lose channel information or how to transform the number of channels to 3?

**Comment by vrabaud** [comment]
You are mis-using imread http://docs.opencv.org/modules/highgui/doc/reading_and_writing_images_and_video.html?highlight=imread#imread
You are not using the cv2.CV_LOAD_IMAGE_UNCHANGED parameter as mentioned here:
http://docs.opencv.org/doc/tutorials/introduction/display_image/display_image.html
(or any negative number would do)
Please close if that solves it for you.

**Comment by NumesSanguis** [comment]
@vrabaud The imread was just an example how I got a 3 channel information gray image with which cv2.resize() works without losing channel information. In my actual program I don't use imread and I use:
cv_image = self.bridge.imgmsg_to_cv2(image, 'mono8') (from a camera)
and here cv_image.shape has (480, 640, 1). Using cv2.resize(cv_image, (250, 240)) for example gives as output: (250, 240) (no channel information) and this new image cannot be send over CvBridge, because CvBridge requires channel information.

**Comment by vrabaud** [comment]
on which ROS distribution are you ?

**Comment by NumesSanguis** [comment]
Ubuntu 12.04, ROS Hydro, OpenCV 2.4.9

**Comment by vrabaud** [comment]
please confirm that master indeed fixes your bug

**Comment by NumesSanguis** [comment]
Sorry for my late reply, but this indeed fixes gray images without channel information. Thank you for your fast responses!
However now when I use bridge.imgmsg_to_cv2() in another ROS node which listens to the gray image data (which doesn't send channel information anymore), suddenly an extra channel is added and (270, 270) becomes (270, 270, 1).
This can be solved by np.squeeze(gray_image), but I can imagine that this is not really a clean way.

**Comment by vrabaud** [comment]
right, you could do that. Now, the problem is I don't thin OpenCV/Numpy has a standard on how many dimensions a 1-channel image has. If you can find one, please let me know and I'll fix it. I'd rather keep 3 dimensions for now as it is explicit. Please let me know what you think.

**Comment by NumesSanguis** [comment]
I don't know if you could call it a standard, but from my use it seems to be that for OpenCV:
Color: (x, y, 3 channels)
Gray: (x, y) (no channels)
After your fix you can send (x,y,no channel) which is great! but it seems that CvBridge now adds a channel when you convert this image back to OpenCV. Maybe an idea is to add a mono8 option with 0 channels?

In OpenCV when using RGB2GRAY and when properly imread(image, 0), then the output is (x, y) (no channels)

**Comment by vrabaud** [comment]
https://github.com/ros-perception/vision_opencv/commit/51701a6762cc1d661706798daf979f17c1029b97  exposes the behavior you mention

**Comment by NumesSanguis** [comment]
Sorry that I didn't respond anymore, but this indeed fixes it!
Thanks a lot!

**Comment by vrabaud** [comment]
thx !
