### ISSUE TITLE
Error: ‘EQUIDISTANT’ is not a member of ‘sensor_msgs::distortion_models’.

### ISSUE THREAD

**Issue by huangjiafengx** [ros-perception/vision_opencv#502]
![image](https://user-images.githubusercontent.com/92708152/203226399-4b372d73-cc05-4cb7-a782-806e580b8830.png)

Hi,  when I build the source code by colcon, it show Error: ‘EQUIDISTANT’ is not a member of ‘sensor_msgs::distortion_models’.

**Comment by huangjiafengx** [comment]
The Env:
ubuntu20.04 (docker)
ros2-foxy
openvino2022
source branch  foxy

**Comment by ijnek** [comment]
What do you get when you run ``ros2 pkg xml sensor_msgs | grep version``?
If you have the most recent sensor_msgs package on foxy, you should get
```sh
<version>2.0.5</version>
```
If you see something older than that, you should upgrade the ros packages via ``apt-get upgrade``.

**Comment by huangjiafengx** [comment]
Thank you,  it is fine to solve.
