### ISSUE TITLE
Check for OpenCV 4 in ROS Melodic

### ISSUE THREAD

**Issue by Shobuj-Paul** [ros-perception/vision_opencv#508]
ROS Melodic OpenCV defaults to /usr/include/opencv instead of checking for /usr/include/opencv4.

Platform: Jetson Nano
OS: Jetpack 4.6.3 (Ubuntu 18.04)

**Comment by Tindahood** [comment]
Any reason why it hasn't been merged by now? Would also solve a problem for my workgroup

**Comment by ijnek** [comment]
Closing out as melodic has reached EOL.
