### ISSUE TITLE
error in anaconda virtual environment

### ISSUE THREAD

**Issue by Ocamyyyy** [ros-perception/vision_opencv#523]
after installing the cv_bridge with python3 of Ubuntu18.04, I can use cv_bridge normally by the system's python3. However, when I change the interpreter to a virtual environment python3.7 in anaconda and even remember sourcing the building result of cv_bridge, the result of code "from cv_bridge.boost.cv_bridge_boost import getCvType" is segment error.
`Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cv_bridge.boost.cv_bridge_boost import getCvType
段错误 (核心已转储)
`

**Comment by ijnek** [comment]
Do you have some more details of ros versions, and whether you're using a source build or binary build?

Two things to note though:
* Ubuntu 18.04 is no longer supported by any of the ROS distros. Things will likely still work if you are using binaries, or building the correct branch from source. 
* ROS installations typically rely on the Python version that comes pre-installed with the operating system, so if you're lucky, things may work with a different python version.

**Comment by ijnek** [comment]
Closing out, as no details were provided.
