### ISSUE TITLE
Magic number in `getConversionCodes()`

### ISSUE THREAD

**Issue by galou** [ros-perception/vision_opencv#532]
There is a magic 5 in [`getConversionCodes()`](https://github.com/ros-perception/vision_opencv/blob/a34a0c261984e4ab71f267d093f6a48820801d80/cv_bridge/src/cv_bridge.cpp#L154). Shouldn't it actually be 10, the last index of the `Encoding` enum?

Anyway, a comment should be added explaining the number there.

**Comment by ijnek** [comment]
Sorry it took so long to get a response on this issue - you're right, it should be 10.

**Comment by galou** [comment]
Thanks for the fix! Time does not matter. You didn't get paid for it I guess.
