### ISSUE TITLE
ROS2 Jazzy includes

### ISSUE THREAD

**Issue by ndahn** [ros-perception/vision_opencv#536]
In ROS2 jazzy the includes for `cv_bridge` and `image_geometry` have changed from `.h` to `.hpp` files. Couldn't test yet, but at least it compiles now! :)

**Comment by ijnek** [comment]
@ndahn could you elaborate on what the issue is?

**Comment by ndahn** [comment]
Sorry, I realize I posted this in the wrong place 👀 Closing.
