### ISSUE TITLE
opencv2 should not work as rosdep

### ISSUE THREAD

**Issue by bmagyar** [ros-perception/vision_opencv#68]
The following job passes on the prerelease test, yet fails on jenkins: 
http://jenkins.ros.org/job/ros-jade-aruco_binarydeb_utopic_i386/2/

The package.xml has: <depend>opencv2</depend> 
Which instead should be <depend>libopencv-dev</depend>

**Comment by vrabaud** [comment]
`rosdep resolve opencv2` gives an error so I am not sure on how you could release something in the first place.
