### ISSUE TITLE
How to send CV_32F images (like depth images) w/ cv_bridge?

### ISSUE THREAD

**Issue by filipetrocadoferreira** [ros-perception/vision_opencv#74]
How can I send CV_32F images (I want to send depth information that usually is the distance in meters stored in 32bits float) but I'm facing problems to use cv_bridge to deal with this.

**Comment by vrabaud** [comment]
As long as you don't explain your problem, your question is generic and should be asked on http://answers.ros.org/ with more details.

**Comment by vrabaud** [comment]
Please provide a piece of code that fails for you, or an explanation. Thx.
