### ISSUE TITLE
any documents?

### ISSUE THREAD

**Issue by k-okada** [ros-perception/vision_opencv#80]
@kochigami is looking for the documents for edge detector in opencv_apps, I think @aginika is about to writing that.

**Comment by aginika** [comment]
@k-okada http://wiki.ros.org/opencv_apps
I wrote it.

**Comment by vrabaud** [comment]
lgtm, thx !

**Comment by k-okada** [comment]
I have updated the wiki pages, http://wiki.ros.org/opencv_apps. Any comments are welcome.
