### ISSUE TITLE
Wrong conversion from MONO16 to BGR8

### ISSUE THREAD

**Issue by stfuchs** [ros-perception/vision_opencv#83]
Noticed that when I was trying to visualize some MONO16 images with rqt_image_view.
After some digging I found that rqt_image_view first tries to convert the input image to BGR8 using the cv_bridge functions.

There is a bug in the ordering when trying to perform color conversion with images of different depths. I've prepared a patch. Will send a PR.

**Comment by vrabaud** [comment]
Hi though your PR was ok for your case, it would not work for the reverse. Plus, there was a big bug in the code (SAME_FORMAT could be called twice). I fixed the tests and code. Thx for reporting !

**Comment by stfuchs** [comment]
Cool, thanks for fixing.
