### ISSUE TITLE
[cv_bridge] Support 32SC1 to visualize in cvtColorForDisplay

### ISSUE THREAD

**Issue by wkentaro** [ros-perception/vision_opencv#90]
I think 32SC1 is usually used for label image, and label image should be visualize with converting it to RGB image.
like [skimage.color.label2rgb](http://scikit-image.org/docs/dev/api/skimage.color.html#label2rgb)

**Comment by vrabaud** [comment]
and max_image_value could indicate the number of clusters ?

**Comment by wkentaro** [comment]
Yeah, at most cases. However sometimes there are other cases (ex label: `0, 1, 3, 5` missing 2 and 4)
