### ISSUE TITLE
Installation of ros-indigo-opencv3 breaks existing OpenCV 2 packages

### ISSUE THREAD

**Issue by meyerj** [ros-perception/vision_opencv#91]
We have an indigo package that uses image_transport to subscribe to an image topic, converts it to an OpenCV type and then internally uses OpenCV directly to work with the images. The scenario is pretty much the same as in the example ROS node of the [Using CvBridge To Convert Between ROS Images And OpenCV Images](http://wiki.ros.org/cv_bridge/Tutorials/UsingCvBridgeToConvertBetweenROSImagesAndOpenCVImages#cv_bridge.2BAC8-Tutorials.2BAC8-UsingCvBridgeCppHydro.An_example_ROS_node) tutorial.

There are several problems as soon as ros-indigo-opencv3 is installed on the system. It took us some time to figure that out, because the opencv3 package was installed as a dependency of another package for a completely different project.
1. The line
   
   ``` cmake
   find_package(OpenCV REQUIRED)
   ```
   
   in the cmake snippet in http://wiki.ros.org/vision_opencv#Using_OpenCV_in_your_ROS_code always finds the OpenCV 3 installation in `/opt/ros/indigo` from now on, which is bad. We observed all kind of consequences ranging from compilation errors, linker errors to segfaults, especially in combination with ros-indigo-cv-bridge, which is linked against the system installation of OpenCV 2.4.8.
   
   The workaround would be to add a specific version requirement, like
   
   ``` cmake
   find_package(OpenCV 2.4.8 EXACT REQUIRED)
   ```
   
   or to rely on `cv_bridge` or `image_geometry` to link to the correct version of opencv indirectly as recommended in the [ROS indigo migration guide](http://wiki.ros.org/indigo/Migration#OpenCV).
2. Even if you somehow can avoid that cmake picks up the OpenCV 3 installation in `/opt/ros/indigo`, the preprocessor will still prefer the headers found in `/opt/ros/include/opencv2` (installed by ros-indigo-opencv3) over `/usr/include/opencv2` from now on whenever it finds a
   
   ``` cpp
   #include <opencv2/core/core.hpp>
   ```
   
   like in [cv_bridge.h:43](https://github.com/ros-perception/vision_opencv/blob/f5f167492a8e4beac28c2dc7567f5e4b163fa4aa/cv_bridge/include/cv_bridge/cv_bridge.h#L43), because some dependency will always add `/opt/ros/indigo` to the include path.
   
   The only workaround I found so far is the following cmake snippet:
   
   ``` cmake
   find_package(OpenCV 2.4.8 EXACT REQUIRED)
   include_directories(
    include
    ${OpenCV_INCLUDE_DIRS}        # /usr/include/opencv;/usr/include
    ${catkin_INCLUDE_DIRS}        # contains /opt/ros/indigo/include
    # ...other include directories
   )
   ```
   
   to make sure that the OpenCV 2.4.8 headers in `/usr/include` are ordered before any other packages' headers.

Probably the situation is the same in ROS jade.

Possible solutions:
- Rename the cmake config provided by ros-indigo-opencv3 to OpenCV3 to avoid collisions with the system version or update all wiki pages and tutorials and recommend to add an exact version to all `find_package(OpenCV ...)` lines.
- Install OpenCV3 headers to `/opt/ros/indigo/include/opencv3` instead of `/opt/ros/indigo/include` directly.

This would of course break new packages using ros-indigo-opencv3, but that might be acceptable as it was only released a few weeks ago.

Related:
- https://github.com/ros-perception/vision_opencv/issues/79
- http://answers.ros.org/question/214043/use-ros-indigo-opencv3-alongside-248/
- http://answers.ros.org/question/213925/opencv30-ros-indigo/

**Comment by vrabaud** [comment]
1 got fixed on the wiki.
2 got fixed with OpenCV 3.1 and a better packaging on my hand.
Please open up a new bug if you find new issues, thx for reporting, that was helpful !
