### ISSUE TITLE
[cv_bridge] Colorized depth image with cvtColorForDisplay?

### ISSUE THREAD

**Issue by wkentaro** [ros-perception/vision_opencv#94]
like http://stackoverflow.com/questions/13840013/opencv-how-to-visualize-a-depth-image

![image](https://cloud.githubusercontent.com/assets/4310419/11919465/01e7d610-a797-11e5-94a4-a47fb72ea22f.png)

How should I apply that option? Do you have any idea?

**Comment by vrabaud** [comment]
Well, to get more complex options, we need to have a struct that contains display options (right now, we only have a few arguments that we pass along). So, just create a struct for display options and it should have members like: do_dynamic_scaling, min_image_value, max_image_value, color_map (which would be -1 by default but JET in your case). No ?

**Comment by wkentaro** [comment]
+1

**Comment by vrabaud** [comment]
Well, feel free to break the API :) I am sure we'll be able to handle more cases with that.

**Comment by wkentaro** [comment]
All right :+1:

**Comment by wkentaro** [comment]
done https://github.com/ros-perception/vision_opencv/pull/130
